# Generated by Django 5.1.3 on 2024-11-24 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_haridor'),
    ]

    operations = [
        migrations.CreateModel(
            name='M',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=50)),
                ('bio', models.TextField()),
                ('rasm', models.ImageField(upload_to='m/')),
            ],
        ),
    ]
