# Generated by Django 5.1.3 on 2024-11-25 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_m'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=50)),
                ('bio', models.TextField()),
                ('rasm', models.ImageField(upload_to='mol/')),
            ],
        ),
        migrations.DeleteModel(
            name='M',
        ),
    ]
